#!/bin/bash

number=600851475143
factor=0

function get_smallest_prime {
    sqrt_n=$(echo "sqrt($1)" | bc)
    for (( i = 2; i < $sqrt_n; i++)); do
        if [[ $(( $1 % $i )) = 0 ]]; then
            factor=$i
            return
        fi
    done
    factor=$1
}

while [ $number -gt $factor ]; do
    get_smallest_prime $number
    number=$(( $number / $factor ))
done

echo $factor